### ISSUE TITLE
Support more combination of torch and torchvision

### ISSUE THREAD

**Issue by da-liii** [liga-ai/liga-pytorch#15]
See https://libraries.io/pypi/liga-pytorch/0.2.0

Here are the deps for liga-pytorch 0.2.0:
+ ligavision 0.2.0
+ torch 1.12.1
+ torchvision 0.13.1

The combination of torch and torchvision is fixed. It would be nicer to support more:
https://github.com/pytorch/vision

**Comment by da-tubi** [comment]
For Google Colab, it is:
+ torch 1.13.1
+ torchvision 0.14.1

**Comment by da-tubi** [comment]
For DBR 11.3 ML:
+ torch 1.12.1
+ torchvision 0.13.1

**Comment by da-tubi** [comment]
For DBR 10.4 ML LTS:
+ torch 1.10.2
+ torchvision 0.11.3

**Comment by da-tubi** [comment]
closed by #16
